project_id = "laowfqzazxgxnkknsvzx"

[functions.telegram-invite]
verify_jwt = false

[functions.telegram-revoke]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.manage-settings]
verify_jwt = false

[functions.receipt-storage]
verify_jwt = false

[functions.data-api]
verify_jwt = false
